### ISSUE TITLE
[AVM Module Issue]: UAMI Role Assignment for Network Related Actions Missing

### ISSUE THREAD

**Issue by senavar** [Azure/terraform-azurerm-avm-ptn-aks-production#102]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### Description

If using bring your own network, UAMI, and deploying using IaC (non-AZ CLI), the AKS docs state that: `If you're using an ARM template or another method, use the principal ID of the managed identity to perform a role assignment. ` 

Goes on further to say: `For a VNet, attached Azure disk, static IP address, or route table outside the default worker node resource group, you need to assign the Network Contributor role on the custom resource group.` 

Ref: [Add a role assignment for a system-assigned managed identity](https://learn.microsoft.com/en-us/azure/aks/use-managed-identity#assign-an-azure-rbac-role-to-the-system-assigned-managed-identity)  

If a user forgets to do this, the future deployment of K8s network related resources like Istio External Gateway or NGINX ingress with the application routing add-on, will end up in a failed state due to missing RBAC permissions. 

I recommend an update to this module to either:
- Mention this in the documentation of the module as a note/warning/reminder
- Add the role assignment for Network Contributor

**Comment by senavar** [comment]
Adding for tracking, already mentioned in PR #103: 

I think the network contributor role needs to be scoped for the entire RG to allow for greater flexibility. For example, if using user-assigned NAT gateway the UAMI needs permission to do action upon the NAT Gateway when deploying a service type LoadBalancer via the application routing add-on. Here is an example where the UAMI has access to the vNet but not the NAT GW:

<img width="456" alt="image" src="https://github.com/user-attachments/assets/6c13ce05-fab5-417d-9925-a17caf225506">

**Comment by zioproto** [comment]
Update: @senavar is from our team. We are working together on PR #103

**Comment by kewalaka** [comment]
> Adding for tracking, already mentioned in PR [#103](https://github.com/Azure/terraform-azurerm-avm-ptn-aks-production/pull/103):
> 
> I think the network contributor role needs to be scoped for the entire RG to allow for greater flexibility. For example, if using user-assigned NAT gateway the UAMI needs permission to do action upon the NAT Gateway when deploying a service type LoadBalancer via the application routing add-on. 

Hi @senavar  - this isn't what I would expect, and doesn't seem to follow least privilege?

If an op wants to bring their own NAT gateway, isn't it their responsibility to assign `Network Contributor` to this resource?

This would be the same as if the op wanted to use a static IP address, too.

I have also raised this here;

https://github.com/MicrosoftDocs/azure-aks-docs/issues/110

Sorry to bring back a closed issue - but I was wondering where this decision to set permissions at the RG came from...
