### ISSUE TITLE
[AVM Module Issue]: Add access to container registry via private endpoint

### ISSUE THREAD

**Issue by AcceleratorFramew0rk** [Azure/terraform-azurerm-avm-ptn-aks-production#107]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Description

Add access to container registry via private endpoint

**Comment by zioproto** [comment]
hello @AcceleratorFramew0rk 
this seems to be a valid feature request. Would you like to open a PR for the maintainers to review ?

**Comment by kewalaka** [comment]
#115 would help accomplish this, as the AVM module for ACR supports private endpoints via the standard interface

**Comment by nellyk** [comment]
This has been added in #119
