### ISSUE TITLE
[AVM Question/Feedback]: Do you plan disable the VNET creation?

### ISSUE THREAD

**Issue by fjvela** [Azure/terraform-azurerm-avm-ptn-aks-production#112]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Hello!

I'm using the module to deploy a hub / spoke solution. I want to use the AKS module but there is not an option to disable the creation of the VNET.

Have you plan anything to allow disable the creation?

Best regards,

**Comment by fjvela** [comment]
Welcome @nellyk !

I think the module is great because you can deploy an AKS cluster very fast: VNET, subnet, ACR, AKS...

But if you want to use the module in other type or topology like a Hub-spoke https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks/baseline-aks#network-topology, you can´t use it because I can´t user my own VNET or my ACR.

If you check the diagram, I´m going to create the VNET, subnet or ACR outside the module, I need some properties to setup it.

I don´t know if you planned it, or if you planned to create another AKS module in order to support it.

Best regards!

references:
- https://learn.microsoft.com/en-us/azure/architecture/networking/architecture/hub-spoke?tabs=cli
- https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks/baseline-aks#network-topology

**Comment by fjvela** [comment]
I´m closing the issue. I´m seeing there are several proposals to do it: https://github.com/Azure/Azure-Verified-Modules/issues?q=is%3Aissue+is%3Aopen+kubernetes

Best regards!

**Comment by nellyk** [comment]
@fjvela we will merge this and it make sense when you want to have a vnet with multiple clusters( of course on different subnets)

This PR will not be our top priority right now but we are willing to review your PR if you'd like to work on this.

**Comment by zioproto** [comment]
@fjvela could you please give feedback on PR #124 ? thanks

**Comment by fjvela** [comment]
@zioproto ! great thanks!
