### ISSUE TITLE
[AVM Module Issue]: module should allow for optional AppGw ingress controller

### ISSUE THREAD

**Issue by kewalaka** [Azure/terraform-azurerm-avm-ptn-aks-production#118]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### (Optional) Module Version

0.1.0

### Description

Many production deployments require some form of defense in depth for internet facing workloads.  If using Azure components, that typically translates to an app gateway with WAF in front of Kubernetes.

I think this would work best as an example illustrating how to 'bring your own AppGw', and a small adjustment to the module to accommodate this as a toggle variable.

**Comment by zioproto** [comment]
We are using Azure CNI Overlay in this module which is not compatible with Application Gateway.

https://learn.microsoft.com/en-us/azure/aks/azure-cni-overlay?tabs=kubectl#limitations-with-azure-cni-overlay
