### ISSUE TITLE
[AVM Module Issue]: Ability to configure AKS configuration parameter using avm-ptn-aks-production 

### ISSUE THREAD

**Issue by puneetdevadiga** [Azure/terraform-azurerm-avm-ptn-aks-production#130]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### (Optional) Module Version

0.2.0

### Description

Problem Statemen: Current AKS production pattern does not allow configuration for certain AKS parameter

Requirement: We have a customer who wants to be able to configure following AKS parameters 

Values should be configurable like
- Network plugins
- Network mode
- pod CIDR
- Service CIDR
- DNS
- taints and labels in nodepool
- SKU

Enabling or disabling
- auto_scaler_profile
- private clusters
- public access
- OIDR_issuer for federated
- AD auth and RBAC
- workload_identity_enabled

**Comment by zioproto** [comment]
hello @puneetdevadiga 

please read the blog post where we explain the design of this pattern module:
https://techcommunity.microsoft.com/t5/azure-for-isv-and-startups/how-to-deploy-a-production-ready-aks-cluster-with-terraform/ba-p/4122013

We are not going to disable private cluster, or change the network modes and plugins. This module enforces those choices.

If you are looking for a module that is fully customizable and supports any AKS feature, I suggest to look into https://github.com/Azure/terraform-azurerm-aks

From the list you shared above the only actionable items are

 * node_taints
 * `auto_scaler_profile`: we can add more configuration options but we are keeping the `balance_similar_node_groups` hardcoded to `true`.
 * SKU: if you mean the SKU of the default node pool, we can add some flexibility, but we are not going to allow any SKU with too little resources.

I believe the Pid CIDR is already configurable. Also `dns_prefix` is already configurable. Could you please clarify those 2 points ? 

Remember, this is an opinionated pattern module for generic production scenarios.

thanks
