### ISSUE TITLE
[AVM Question/Feedback]: Please add valid source in All 3 example

### ISSUE THREAD

**Issue by nrv-96** [Azure/terraform-azurerm-avm-ptn-aks-production#53]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Hello Team,

I have checked and found that all 3 examples don't mention the valid source in [registry.terraform](https://registry.terraform.io/modules/Azure/avm-ptn-aks-production/azurerm/latest/examples/with_availability_zone#:~:text=source%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3D%20%22../../%22). Source should be `Azure/avm-ptn-aks-production/azurerm` instead of ` source  = "../../"`

This above change will need to be done in the below file:
1. examples/default/main.tf 
2. examples/with_availability_zone/main.tf 
3. examples/without_availability_zone/main.tf

**Comment by zioproto** [comment]
Hello @nrv-96

thanks for opening the issue.

the form `../../` is actually correct. The examples are run in the GitHub action to test the PRs from this repo.

Referring to `../../` makes possible to test the actual code changes proposed in each PR.

Please let me know if you have any question.

**Comment by nrv-96** [comment]
@zioproto ,

Could you please update into Terraform site? As the blank source for the end user is confusing things.
![image](https://github.com/Azure/terraform-azurerm-avm-ptn-aks-production/assets/62826272/f9dab938-2944-4d4e-93bb-4b35d3d9d92a)

**Comment by zioproto** [comment]
The terraform site:
https://registry.terraform.io/modules/Azure/avm-ptn-aks-production/azurerm/latest/examples/with_availability_zone

is autogenerated, so we can't change what is published in the website.
