### ISSUE TITLE
Allow users to use a custom name for their virtual network

### ISSUE THREAD

**Issue by JamesDLD** [Azure/terraform-azurerm-avm-ptn-aks-production#82]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Description

Allow users to use a custom name for their virtual network and fit with their naming convention.
Naming convention is a standard of clients, as a reference we can quote the following documentation: [Azure - CAF - Naming convention](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming?WT.mc_id=AZ-MVP-5003548)

**Comment by nellyk** [comment]
Thanks @JamesDLD  for your PR this has now been merged #83
